

name = "tom"

# try:
#     int(name)
#
# except ValueError as ex:
#     print(ex)
#


try:
    int(name)

except Exception as ex:
    print(ex)


